[project]
name = "comfyui-text"
description = ""
version = "1.0.0"
license = "LICENSE"

[project.urls]
Repository = "https://github.com/LZpenguin/ComfyUI-Text"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "lzpenguin"
DisplayName = "ComfyUI-Text"
Icon = ""
